language: swift  #1
script: 
- xcodebuild clean build test -sdk iphonesimulator -workspace MediaRemoteControl.xcworkspace -scheme MediaRemoteControl CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2' -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2'
osx_image: xcode8.2 #2
xcode_workspace: MediaRemoteControl.xcworkspace #3
xcode_scheme: MediaRemoteControl #4
xcode_sdk: iphonesimulator10.2 #5